#### 1.前处理，定义网格

In [58]:
import numpy as np

# 计算域长度
length = 1.0

# 网格大小
iCell=10
jCell=4

iVertex = iCell + 1
jVertex = jCell + 1

dx = 1/iCell
dy = 2*dx

x = np.zeros([jVertex, iVertex])
y = np.zeros([jVertex, iVertex])

xc = np.zeros([jCell, iCell])
yc = np.zeros([jCell, iCell])

si = np.full((jCell, iVertex), dy)
sj = np.full((jVertex, iCell), dx)

for j in range(jVertex):
    x[j, :] = np.linspace(0.0, length, iVertex)

for i in range(iVertex):
    y[:, i] = [j * dy for j in range(jVertex)]

print(x)
print(y)
print(si)
print(sj)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]]
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8]]
[[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]


#### 2. 流场数组及变量定义

In [59]:
# 守恒变量[ρ, ρu, ρv, ρE]
Q = np.ones([iVertex, jVertex, 4])

# 原始变量[ρ, u, v, p]
d = np.ones([iVertex, jVertex])
u = np.zeros([iVertex, jVertex])
v = np.zeros([iVertex, jVertex])
p = np.ones([iVertex, jVertex])

# 比热
gaiVertexiVertexa = 1.4
